### ISSUE TITLE
Add how-to on creating a generator from scratch

### ISSUE THREAD

**Issue by 7sharp9** [MoiraeSoftware/myriad#102]

**Comment by travis-leith** [comment]
I have an idea for a case study that would make a good how-to.

A generator that, given a DU type `'a` with individual cases of types '`b, 'c, 'd, ...`, can generate a function with the signature 
`a' seq -> 'b list * 'c list * 'd list * ...`

The function takes a DU type sequence and splits it into separate lists for each case.

**Comment by 7sharp9** [comment]
tuplising things or listifying things was a plugin that aI would like to do.  Such as:

```
[Myriad.tuple]
myType = ...
let test = mYTpe.create ...

let tupled = MyType.toTuple test
let result = MyType.fromTuple tupled
```
