### ISSUE TITLE
Allow control of Lens generator style to match Aether style

### ISSUE THREAD

**Issue by travis-leith** [MoiraeSoftware/myriad#103]
Currently, myriad produces lens setter with signature `'b -> 'a -> 'b`. Aether provides a bunch of utilities for working with Lenses, but does not actually create the Lenses. It assumes setters have the signature `'a -> 'b -> 'b`.
I would be nice if I could use myriad to generate Lenses which can be used by Aether.
Maybe an additional attribute to indicate the lens style?

**Comment by 7sharp9** [comment]
Done via #110
