### ISSUE TITLE
[docs] How to build the docs pages locally?

### ISSUE THREAD

**Issue by 64J0** [MoiraeSoftware/myriad#135]
I want to contribute to this project by providing a menu to make it easier to navigate on the docs page. How can I test it locally?

**Comment by 7sharp9** [comment]
No idea yet, refers just markdown in folders so far, it needs integration into the GitHub pages, I imagine  this is a build and push to a branch with the right name?   Hugo build would build everything if it was called from the correct location, the subfolders would be hierarchical pages I think…?

**Comment by 64J0** [comment]
> I imagine this is a build and push to a branch with the right name?

Ok, so this is the way you are deploying this page. I'm not sure if I can reproduce it locally btw, need to search more about this.

> Hugo build would build everything if it was called from the correct location, the subfolders would be hierarchical pages I think…?

Oh, nice, thanks man, I'll take a look at the hugo docs and try to build the site locally https://gohugo.io/getting-started/quick-start/. For now, I have noticed that we still have access to the same pages as before, just need to place the right URL like this: https://moiraesoftware.github.io/myriad/content/tutorials/configuration.html.

If we can make a default component that is replicated to all the other pages it would make our life much easy since we could just place this navigation menu there.

**Comment by 7sharp9** [comment]
hugo server from the docs folder will run the docs generation and run a server to test.

**Comment by 7sharp9** [comment]
Adding need`NeedDocs` for the docs for the docs :-)

**Comment by 7sharp9** [comment]
Docs are just Hugo so its just a matter of running Hugo
