### ISSUE TITLE
Myriad di deploy di server mana? app.myriad.social

### ISSUE THREAD

**Issue by fakhryhizballah** [MoiraeSoftware/myriad#141]
![Screenshot_2022-03-13-22-18-58-53_8f7df597d46828da05903710a4aa4513](https://user-images.githubusercontent.com/50532299/158066618-779428da-bc96-49f7-80dd-69e931706a4f.jpg)

![Screenshot_2022-03-13-22-18-21-11_8f7df597d46828da05903710a4aa4513](https://user-images.githubusercontent.com/50532299/158066620-9da517d1-0da8-443f-8b32-af321e087076.jpg)

Data login kita di simpan di mana?

**Comment by 7sharp9** [comment]
Closing as dunno what this is.
