### ISSUE TITLE
Allow inline generation with custom placement

### ISSUE THREAD

**Issue by cmeeren** [MoiraeSoftware/myriad#145]
My project structure is generally like this:

```
- Domain.User.fs
- Domain.Order.fs
- ...
```

Each `Domain*` file contains first the types relating to the domain (e.g. the `User` type itself), then the modules with functions (e.g. the `User` module).

I want to use the lens generator. However, it seems like currently, Myriad can only output to either a separate file or the end of an existing file. That means that since the domain modules use lenses, I will have to double the amount of files in my project (e.g. `Domain.User.Types.fs` with Myriad output at the end and `Domain.User.Functions.fs` after that). Instead, I want the lenses generated in each domain file _below_ the types but _above_ the modules that use the lenses.

It would therefore be great if Myriad provided an option for me to specify where to insert the generated code.

For example:

```f#
[<Generator.Lenses("lens")>]
[<Generator.OutputInlineBetween("myriad-start-lenses", "myriad-end-lenses")>]
Type User = ...

// myriad-start-lenses

// myriad-end-lenses
```

Above, I manually add the comments `myriad-start-lenses` and `myriad-end-lenses` to the source file, and specify to Myriad using a new attribute `OutputInlineBetween` that specifies what Myriad searches for. (Myriad can fail if finding no or multiple matches.) Myriad then replaces everything between the matching lines with the generated output.

Ideally, Myriad should respect the indentation of the comments. For example:

```f#

module User =
  // myriad-start-lenses

  // myriad-end-lenses
```

Above, Myriad should insert the code at the same indentation level as the comments.

Ideally it should also be able to specify the same start/end comments for multiple generators, and Myriad then places the output for all of them in the specified location.

**Comment by 7sharp9** [comment]
One of the problems with this is plugins currently use `<MyriadInlineGeneration>true</MyriadInlineGeneration>` which passes a command line option to the myriad sdk which modifies the way the output of the plugin is used.  If an attribute is used then the plugin would have to be pre processed so that Myriad knew where to put the code.  

Another problem is Fantomas is used to format the code so theres only the options that fantomas can accept to alter its output so Myriad would probably have to count the indentation in the start/end comments _(What if they differ)_ and then write line by line the output with the indentation as prefix.

Reusing the start/end for multiple generators, this sounds the hardest, how would any plugin know if another plugin had already generated code in that start/end, Myriad would probably have to keep track of this information, or, filter plugins by generation type (newFile, inline, inlineStart/End) and process each type sequentially.  In the case of the inlineStart/End you would be adding the contents of the file up to the start comment, appending all plugins for that start/end, then inclusively adding the code following the end block.

**Comment by 7sharp9** [comment]
I'm going to go ahead and say I probably won't implement this.  Ir seems to be a very niche case and would not add much to the overall scope of myriad, yet take a lot of effort to think about and implement.

**Comment by cmeeren** [comment]
Understandable. I think [F# RFC FS-1023 Allow type providers to generate types from types](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1023-type-providers-generate-types-from-types.md) is ideal for what I want, though unfortunately not immediately on the horizon.

**Comment by 7sharp9** [comment]
Yes it’s been dormant for years now.   I don’t rule out this feature, but I would probably require assistance.

**Comment by cmeeren** [comment]
From your perspective, is there a way to modify my request to make it more feasible to implement? For example, I'm fine with not using attributes. My goal is to be able to generate lenses without doubling the amount of files in m codebase. In other words, I'd like to stick with `Domain.User.fs` which contains (in order) types, lenses, and functions, instead of needing `Domain.User.Types.fs` containing types and lenses, and `Domain.User.Functions.fs` containing the functions. (That would also prevent me from using the `private` modifier on types that should only be internally accessible to the `User` module functions, since they are then defined in a separate file.)

**Comment by 7sharp9** [comment]
So why can’t intrinsic extensions appear at the end, because of the added modules after, or because of the namespace they are in rather than a rec module etc?   I’m mainly hesitant because I’m writing to users files, I don’t want to break things!

**Comment by cmeeren** [comment]
My `Domain.User.fs` file is like this:

```f#
type User = { Id: UserId; Username: Username; FirstName: FirstName; ... }

module User =

  let create ...

  let setFirstName ...
```

So: The `User` type definition first, then a module with the same name that contains functions for whatever you can do with a `User`. It's these functions that use lenses. I currently have my lenses (manually) defined at the top of the `User` module.

If I am to use Myriad for generating lenses (which I'd like to, because lens definitions are completely mechanical), I need the lenses defined between the type and the module. Currently, the only ways to do that are 1) make the top-level namespace/module in the file recursive, which means Intellisense is less helpful and I'll lose out on one of the great benefits of F#, or 2) split the file into one file for the `User` type definition + Myriad-generated lenses at the end, and another file for the `User` module with all the functions, which means I can't have `type User = private { ... }` in order to properly protect the internals/invariants of the `User` type.

**Comment by 7sharp9** [comment]
Yep, leave it with me I'll have a think, probably a marker attribute specified in the generator might be better than comments.  

Incidentally, Intrinsic type extensions added to TypeProviders also has a use in this area, thats why I initially worked on that RFC and compiler PR  :-)

**Comment by 7sharp9** [comment]
Also, if I could rely on compiler parsing of the type, they could be placed after the type definition is finished, sometimes F# range of the type in the AST reports the wrong range though `[<Generate(InlineAfter)>]` would of been perfect.

**Comment by 7sharp9** [comment]
Just checked with ast output on a simple record and it looks like the range starts dis correct so this may be an option, an attribute starting inline after the attributed type.

**Comment by 7sharp9** [comment]
The problem with this is the lack of an end to the generated code so myriad knows what to cut out the next time it runs.

**Comment by cmeeren** [comment]
This may be a bad idea, but how about decorating all the Myriad-generated members with a marker attribute? Then you can remove those (wherever they are) and insert them at the start. If users happen to insert custom methods in between Myriad ones, they would just end up at the end.

In any case, I'm not really sure I'm personally that interested in methods on the actual type definition. I like to start by defining all my types at the top of the file, and then all the behavior comes later. This makes it easy for me to see just the type definitions, which generally tells you a lot in F#. If there were many methods in between the type definitions, getting that "overview" of a domain via the type definitions would be harder.
