### ISSUE TITLE
Extensions like SynType.Option generate incorrect syntax

### ISSUE THREAD

**Issue by AlexeyRaga** [MoiraeSoftware/myriad#151]
Using `SynType` extensions from `Myriad.Core.AstExtensions`:

- `SynType.Option(SynType.Int())` generates `Optionint` instead of `Option<int>`
- `SynType.ResizeArray(SynType.Int())` generates `ResizeArrayint` instead of `ResizeArray<int>`

At the same time, postfix notation works fine:
`SynType.CreateApp(SynType.Create("option"), [SynType.Int()], true)` generates `int option` correctly.

**Comment by 7sharp9** [comment]
These issues are probably because generics have never been utilised much yet, thanks for reporting.
