### ISSUE TITLE
Upgrading from 0.5.0 to 0.8.1 removes keywords from many elements

### ISSUE THREAD

**Issue by UnoSD** [MoiraeSoftware/myriad#154]
Hi, I have finally upgraded to 0.8.1 here: https://github.com/UnoSD/Pulumi.FSharp.Extensions/tree/upgrade-myriad and I got it to generate.

Something quite odd is happening; many keywords are disappearing in the generation, for instance:

```fsharp
let componentInfo =
    { SynComponentInfoRcd.Create [ Ident.Create name ] with 
          Attributes = attributes }
SynModuleDecl.CreateNestedModule(componentInfo, content)
```

used to generate:

```fsharp
module name =
```

now it just generates:

```fsharp
name =
```

which obviously does not compile.

Same thing for let bindings where the `let` disappeared and classes where the `member` is also gone. Also some closing parenthesis are not being added anymore.

Happy to try and reproduce on a smaller scale if it helps and you can kindly dedicate some time to this as I appreciate building Pulumi.FSharp.Extensions is quite time/cpu consuming (however setting debug = true in Debug.fs and running `dotnet fake run build.fsx AzureAD` only takes a minute).

Any suggestion is welcome.

Also, not sure if you prefer me to create a separate issue, however also lambdas do not generate any more giving me this error:

```
  OTHER: System.Exception: Unexpected expression: Lambda
    (false, true,
     SimplePats
       ([Id (args, None, false, false, false, unknown (0,0--0,0))],
        unknown (0,0--0,0)),
     Lambda
       (false, true,
        SimplePats
          ([Id (f, None, false, false, false, unknown (0,0--0,0))],
           unknown (0,0--0,0)),
        App
          (NonAtomic, false,
           LongIdent
             (false, LongIdentWithDots ([f], []), None, unknown (1,0--1,0)),
           Ident args, unknown (1,0--1,0)), None, unknown (0,0--0,0),
        { ArrowRange = Some unknown (0,0--0,0) }), None, unknown (0,0--0,0),
     { ArrowRange = Some unknown (0,0--0,0) })
```

from this:

```fsharp
SynExpr.Lambda(false,
               true,
               SynSimplePats.SimplePats(args, range.Zero),
               exp,
               None,
               range.Zero,
               { ArrowRange = Some range.Zero })
```

Used to work well before (the method did not have the `SynExprLambdaTrivia` as extra argument I had to add after upgrading)

Thank you.

**Comment by 7sharp9** [comment]
This is due to fantomas, range.zero elements need to be added to what were previously just `None`, to `Some range.Zero`, basically anything which added syntax trivia.

**Comment by 7sharp9** [comment]
This affects Lambdas, I remembering having to fix those as well as anything else that added trivia.  I call it a breaking changes and bug in Fantomas but they disagreed.

**Comment by UnoSD** [comment]
> ```fsharp
> let componentInfo =
>     { SynComponentInfoRcd.Create [ Ident.Create name ] with 
>           Attributes = attributes }
> SynModuleDecl.CreateNestedModule(componentInfo, content)
> ```

I think I misunderstood, I tried both:

```fsharp
let componentInfo =
    { SynComponentInfoRcd.Create [ Ident.Create name ] with 
          Attributes = attributes
          Range = range.Zero }

SynModuleDecl.NestedModule(componentInfo.FromRcd,
                           false,
                           content,
                           false,
                           range.Zero,
                           SynModuleDeclNestedModuleTrivia.Zero)
```

and

```fsharp
let componentInfo =
    { SynComponentInfoRcd.Create [ Ident.Create name ] with 
          Attributes = attributes
          Range = range.Zero }

SynModuleDecl.CreateNestedModule(componentInfo, content)
```

to add the range, but that didn't help. You mentioned a `Range option`, but those there are just `Range` so I may be missing something (Although I have seen those new options around after upgrading and I will check that they are `Some range.Zero`).

also, how would you fix the runtime error on that lambda?

Thank you.

**Comment by 7sharp9** [comment]
I can see FsAst  in the code above, I dont use that any more, so I reckon that will have broken utility functions due to Fantomas changes. `componentInfo.FromRcd`  etc, that might be tripping you up as the helpers in FsAst generate dud code.

I create nested modules here:  https://github.com/MoiraeSoftware/myriad/blob/0684c0b26f8b5b6943626b2a3a01164ff75e5b6c/src/Myriad.Core/Ast.fs#L344

via the plugins included (Lens one here): https://github.com/MoiraeSoftware/myriad/blob/e120afe46fd1094aa203ce7f055616bddc7aad10/src/Myriad.Plugins/LensesGenerator.fs#L180

**Comment by 7sharp9** [comment]
I think the runtime issue is just due to the syntax tree having changed in F#, the trivia additions and also removal of parts od the simplepat in let bindings I think.  This is the PR I did to upgrade to  net60 and fix the AST changes in both F# and Fantomas' rendering  of them.

**Comment by 7sharp9** [comment]
https://github.com/MoiraeSoftware/myriad/commit/e120afe46fd1094aa203ce7f055616bddc7aad10

**Comment by UnoSD** [comment]
thank you, this worked:

```fsharp
let componentInfo =
    { SynComponentInfoRcd.Create [ Ident.Create name ] with 
          Attributes = attributes
          Range = range.Zero }

SynModuleDecl.NestedModule(componentInfo.FromRcd,
                           false,
                           content,
                           false,
                           Range.Zero,
                           { EqualsRange = Some Range.Zero
                             ModuleKeyword = Some Range.Zero })
```

it's going to be hell to change it everywhere, I agree that's a massive breaking change. I'm tempted to just roll back to the old version for good.

**Comment by 7sharp9** [comment]
I stopped using FSAst before the Fantomas change, I was never happy with the record versions of things, it just seemed so unnecessary, all that was needed was extension methods with optional params.  All of these exist now in Myriad so need for FSAst.

**Comment by UnoSD** [comment]
thank you; I blindly didn't realise that was in the Myriad package. I will switch to that, sounds much simpler.

I will also give a go to the lambda to see if it works with trivia

**Comment by UnoSD** [comment]
I gave it a go; but then I realised that the lambda was never created with FsAst and the trivia was correct (all values to Some). So the problem with the lambda is different, I may play with it a little bit (try and use Myriad.Core.Ast and if that fails I may open a different issue if that's OK)

**Comment by 7sharp9** [comment]
I know lambdas and let binding had ast changes, I think I had the same error in the lens plugin, that has quite a few lambdas in it, nested lambdas.

**Comment by UnoSD** [comment]
I think I got it working now, I'm using your Ast helpers and seems to generate lambdas; still a lot of work to do, but I am removing FsAst.
