### ISSUE TITLE
Plugin path not quoted

### ISSUE THREAD

**Issue by xeotrel2** [MoiraeSoftware/myriad#159]
In the following line, the path to the plugin assembly is not quoted:
https://github.com/MoiraeSoftware/myriad/blob/2ab502950d1848947bf942d2ad566b1cf7072fdb/src/Myriad.Sdk/build/Myriad.Sdk.targets#L219

I ran into this when trying to import a plugin from a path containing a space. It seems to be an easy fix, by placing double quotes around the path as in the lines above it.

Thanks for creating/maintaining this great project!

**Comment by lucasteles** [comment]
Same here
