### ISSUE TITLE
Automatic generation of record variant types

### ISSUE THREAD

**Issue by ShalokShalom** [MoiraeSoftware/myriad#161]
Hi!

I heard Myriad could shorten this:

![Screenshot_20230205_200228](https://user-images.githubusercontent.com/6344099/216840271-fc7feb81-f162-47c0-a72a-b4ef622f3845.png)

The example is from [Scott Wlaschin's site](https://fsharpforfunandprofit.com/posts/designing-with-types-single-case-dus/) and he uses a lot of generic types for couple of the record variants. 

See Address1 and Address2, as an example. 
I want to be as specific as possible, to avoid these two being mixed, as an example. 

Defining an own single case union type for every of that variants becomes tedious. 

So, can we automate that?

**Comment by 7sharp9** [comment]
You would have to annotate in some way so that Myriad knew where and how things were combined (And name rules).  Once you know the rules writing the ast would not be that hard to do.  At that point is would be just a new plugin

**Comment by ShalokShalom** [comment]
So the workflow could be:

I create a record with a type, that has not been created yet. 
Myriad picks this up and puts a single case union above the record. 

Does Myriad have a watch command for this?

**Comment by 7sharp9** [comment]
Myriad would place the code below or in a sibling file.

There is no watch command, the integration runs at compile time, or is you execute Myriad as a dotnet tool.  Msbuild internally does this as part of the integration in Myriad/MSBuild.

**Comment by ShalokShalom** [comment]
Thanks a lot

**Comment by ShalokShalom** [comment]
Could I create the above syntax from the following:

```fs
type PostalAddress =
    { Address
      Address2
      City
      State
      Zip }
```
