### ISSUE TITLE
Documentation on how to create my own plugin?

### ISSUE THREAD

**Issue by travis-leith** [MoiraeSoftware/myriad#166]
The links seem to be broken. https://7sharp9.dev/programming/2019-04-24-applied-metaprogramming-with-myriad/ and https://7sharp9.dev/programming/2019-11-06-myriad-intro/ do not seem to work.
I am assuming these links are intended to help me to write my own plugin? If not, are there any other links?

**Comment by 7sharp9** [comment]
Guess who never paid their domain renewal!

**Comment by 7sharp9** [comment]
The docs that were on my site (Which is now no more) are now in the root:

Applied Metaprogramming with Myriad (I wrote this for the Applied F# Challenge)
Myriad Intro
Myriad Configuration Changes

Hope this helps!
D.
