### ISSUE TITLE
The "Terms of use" in the README seems to violate the Open Source Definition.

### ISSUE THREAD

**Issue by wraikny** [MoiraeSoftware/myriad#170]
The [Apache license 2.0](https://opensource.org/license/apache-2-0/) is an open source license approved by the Open Source Initiative, and the section 5 of the [Open Source Definition](https://opensource.org/osd/) is as follows:

> 5. No Discrimination Against Persons or Groups
> The license must not discriminate against any person or group of persons.

However, in the Terms of use in the README,

https://github.com/MoiraeSoftware/myriad/blob/0822b8bcd277cc3933f97eeef04f66a38c4dd745/README.md?plain=1#L287-L294

which means "If you do not agree with the statements, do not use this project", so it seems to violate the OSD.

There should be no problem unless there are restrictions on users.

I would appreciate your confirmation.

**Comment by 7sharp9** [comment]
Are you suggesting I should chnage the license?

**Comment by wraikny** [comment]
I think either the License or Terms of use would need to be changed to make it no longer a violation of the license.
