### ISSUE TITLE
Publish packages with the latest Fantomas alpha

### ISSUE THREAD

**Issue by gsomix** [MoiraeSoftware/myriad#37]
Hello,

I'm working on plugin that heavily relies on abstract classes generation. There is [blocking issue](https://github.com/fsprojects/fantomas/issues/742) in the latest Fantomas release (3.3) resolved in https://github.com/fsprojects/fantomas/pull/743 (and I hope in the latest Fantomas alpha).

Could you please update Myriad packages since https://github.com/MoiraeSoftware/myriad/pull/35 is merged? 

Thank you in advance!

**Comment by 7sharp9** [comment]
Will be another release today.

**Comment by 7sharp9** [comment]
Released
