### ISSUE TITLE
Namespace repeating in Generated.fs

### ISSUE THREAD

**Issue by TheAngryByrd** [MoiraeSoftware/myriad#38]
The `Generated.fs` file seems to create a namespace for each plugin, even if the plugin has not run.

```fsharp
//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec DataSchema


namespace rec DataSchema


namespace rec DataSchema

{{ My generated code }}

```

Is this intentional?

**Comment by 7sharp9** [comment]
Namespaces should probably be the responsibility of the plugin, although having the namespace in the msbuild file make sit more complex.  Any ideas on reconsolidating this?

**Comment by 7sharp9** [comment]
```xml
<Compile Include="Generated.fs">
    <MyriadFile>Library.fs</MyriadFile>
    <MyriadNameSpace> DataSchema </MyriadNameSpace>
</Compile>
```
So you are using something like that but there are 3 nuget plugins?

**Comment by TheAngryByrd** [comment]
Yeah I have the plugins from https://github.com/MoiraeSoftware/myriad/tree/master/src/Myriad.Plugins and my plugin I'm writing loading. 

I'm thinking we can check if [parsedInput](https://github.com/MoiraeSoftware/myriad/blob/master/src/Myriad/Program.fs#L80) is empty and not write anything if not.

**Comment by TheAngryByrd** [comment]
Oh that won't work nevermind.

**Comment by TheAngryByrd** [comment]
Maybe generators should return a `Some`/`None` whether they should write out or not?

**Comment by 7sharp9** [comment]
Im not convinced `<MyriadNameSpace> DataSchema </MyriadNameSpace>` should exist, but a namespace needs to go somewhere.  Also perhaps it should be an attribute of `MyriadFile`.  

Making the plugin return Some/None could be a good move.  Maybe prefixing try onto the API.

**Comment by 7sharp9** [comment]
I think `MyriadFile` is sufficiently generic that it could be any file, not just and F# one, toml would be a good example.

**Comment by 7sharp9** [comment]
The ns generated by plugins could be grouped and merged, problem I worry about is ordering though.

**Comment by 7sharp9** [comment]
p.s. `MyriadNameSpace` is now obsolete, config based
