### ISSUE TITLE
Plugin loading third party dependencies

### ISSUE THREAD

**Issue by TheAngryByrd** [MoiraeSoftware/myriad#39]
When trying to load information from a third party dependency in a plugin, I'm getting the error:

```
EXEC : error : inputfile Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed doesn not exist
```

How do you think we should go about finding the place to load these 3rd party dependencies?

**Comment by 7sharp9** [comment]
So the plugin is a nuget and its dependencies are not being downloaded?

**Comment by TheAngryByrd** [comment]
Yeah it's a nuget dependency but my guess is where Myriad is being run, it can't find Newtonsoft.Json. I think this is the same problem [F# Analyzers have](https://github.com/ionide/FSharp.Analyzers.SDK#packaging-and-distribution).  

My particular case is I'm running the generator in my test project and just referencing my plugin after build, which doesn't copy all the dependencies.

**Comment by 7sharp9** [comment]
The location of the dll is specified in the `.props` file:
```xml
 <MyriadSdkGenerator Include="$(MSBuildThisFileDirectory)/../lib/netstandard2.1/Myriad.Plugins.dll" />
```
I wonder if we can do something here...?

**Comment by TheAngryByrd** [comment]
Yeah so if I do a publish of my plugin and reference that directory with `MyriadSdkGenerator` it works.  Now I'm just wondering how to make this smooth for my testing project.

**Comment by TheAngryByrd** [comment]
Circling back, doing the recommendation in F# analyzers work and following the guidlines in the README about testing plugins works smoothly.

**Comment by 7sharp9** [comment]
Ive not read it yet, @Krzysztof-Cieslak Anything you would do different now?

**Comment by TheAngryByrd** [comment]
Slight correction about making testing work. 

I had to add:

```xml
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```

to my fsproj. This ensures the build folder contains all the 3rd party dependencies, then loading the plugin via the `InTest.props` file works.

**Comment by Krzysztof-Cieslak** [comment]
In Analyzers.SDK we also use `McMaster.NETCore.Plugins` instead of directly loading stuff with `Assembly.Load` - as far as I remember this was done to allow a different version of dependencies between plugins and host. Part of the problem in the case of Analyzers.SDK was that we need to stay on `netcoreapp2.0`.

I think in context of Myriad one thing to explore would be `AssemblyDependencyResolver` API added in .Net Core 3.1 - https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblydependencyresolver?view=netcore-3.1

**Comment by 7sharp9** [comment]
@TheAngryByrd Was this what you meant?  ^

**Comment by TheAngryByrd** [comment]
I did not know that but it's still useful information

**Comment by 7sharp9** [comment]
Done

**Comment by 7sharp9** [comment]
Maybe we need `AssemblyDependencyResolver` as things seem to have gone awry with dotnet 6.0.  @TheAngryByrd Are you having any issues with your plugins, I forget if your still painting them?

**Comment by TheAngryByrd** [comment]
Sorry, I haven't really touched any of my plugins in years at this point.

**Comment by 7sharp9** [comment]
Stale Bread
