### ISSUE TITLE
Current version not on nuget

### ISSUE THREAD

**Issue by NicoVIII** [MoiraeSoftware/myriad#55]
This is not an issue with Myriad itself but with its deployment.

As far as I can see the Changelog was not updated and therefore the automatic release tried to release the 0.3.1 (tag) as 0.2.8 (changelog) which already existed and was therefore not accepted by nuget.

It would be cool if someone could fix that and release the current version also on nuget.

**Comment by 7sharp9** [comment]
Releases are manual so, after a release tag a version is manually uploaded to nuget.  The 0.3.1 tag was mainly to test the documentation generation.  Its true the change log needs an update, I will have to remember what was changed.  🤔

**Comment by NicoVIII** [comment]
Ah okay.
I had a look at the .github/workflows/publish.yml and thought this would create the nuget release as well but it was only the release creation on GitHub that failed. Sorry!

**Comment by Thecentury** [comment]
@7sharp9 Do you mean a meaningful PR or just any to trigger the publishing?
Asking because I'm looking forward to using the newest additions in my code.

**Comment by 7sharp9** [comment]
I was hoping for meaningful.  I will release another version soonish, I was hoping to do a little on the config side, not had the time lately though.

**Comment by 7sharp9** [comment]
Released as 0.4.0 on nuget.
