### ISSUE TITLE
How to add "and" between types?

### ISSUE THREAD

**Issue by mastoj** [MoiraeSoftware/myriad#60]
Let's say I wanted to generate a bunch of types defined in a json schema, how would I add "and" between the types to make sure they are all available?

The project I'm working on is builder generation for pulumi: https://github.com/mastoj/Pulumi.FSharp.Azure/tree/k8sversion

Where we need to generate types from: https://raw.githubusercontent.com/pulumi/pulumi-kubernetes/master/provider/cmd/pulumi-resource-kubernetes/schema.json

**Comment by 7sharp9** [comment]
To add `and` between types its a s simple as just adding the types to the same `SynModuleDecl.Types` list when you create them.  

```
SynModuleDecl.Types
    ([TypeDefn(ComponentInfo([], [], [], [one], PreXmlDoc (), false, None, range.zero),
         SynTypeDefnRepr.ObjectModel(TyconClass, [], range.zero), [], range.zero)

      TypeDefn(ComponentInfo([], [], [], [two], PreXmlDoc (), false, None, range.zero),
         SynTypeDefnRepr.ObjectModel(TyconClass, [], range.zero)
    ], range.zero)
```

**Comment by 7sharp9** [comment]
If you look at the helpers in `FsAst` in one for greater type you can see a single entry in the input types:

https://github.com/ionide/FsAst/blob/master/src/AstCreate.fs#L331

**Comment by mastoj** [comment]
Awesome, thanks for the quick response. It turned out I didn't need it for my case, but always good to know.
