### ISSUE TITLE
Generate multiple files

### ISSUE THREAD

**Issue by UnoSD** [MoiraeSoftware/myriad#64]
Is there a way to generate multiple files? If not, can you please consider adding this feature?

In my project I'm using Myriad to generate a bunch of computational expression builders from a JSON containing cloud resources (using Pulumi).

This ends up generating a 120000 lines file. It gets quite ugly for the IDE to process that single file.

Thank you.

**Comment by 7sharp9** [comment]
How would that look in terms of generating?  I mean you can already
generate multiple files with the msbuild integration, I assume you mean one
instance generates multiple files.   What would this look like in the
fsproj?

**Comment by UnoSD** [comment]
I was thinking about dynamic generation of files. I know you can add multiple items in the `fsproj`, but that requires upfront knowledge.

In my specific case, the number of files depends on elements from a JSON file. I use the original file for configuration and then generate the output.

Would be nice if there was an `IMyriadGenerator.Generate` method: `string * ParsedInput -> string * SynModuleOrNamespaceRcd []` with the resulting tuple array being: `fileName * ast`; the name of the output files will be generated at runtime then.

The MSBuild task would just take the input file (or potentially even nothing if you don't need any input, maybe the configuration can be specified in attributes on the task).

Something like:

**Project.fsproj**
```
<MyriadGenerate Plugin="plugin.dll" Config="config" />
```

And the output files will be from the output of the Generate call.

Hope that makes sense.

**Comment by 7sharp9** [comment]
So are you running via the cli tool?

It’s working out how ever usage can benefit etc.  There is work to move
config to a toml file soon.

**Comment by UnoSD** [comment]
nope, I'm using the MSBuild task.

I appreciate it may not be the most common use case, people are more likely to just augment existing code rather than generating new types; I was wondering if there was already a way and I wasn't aware.

I could attempt a PR, but I can't promise anything as my spare time is all focused on the `Pulumi.FSharp.Extensions` library, currently.

If that's not too time-consuming I may write my own MSBuild task to split modules from one file to multiple after the generation.

**Comment by 7sharp9** [comment]
It’s figuring out how to do one to many with msbuild then file ordering for
F#.   F# shared asset projects were similar but it’s 4 or 5 years since I
worked at xamarin and that knowledge is forgotten 😬

**Comment by UnoSD** [comment]
File ordering should just follow the order of the sequence returned by the method and should start inserting files after the XML tag. One to many in MSBuild... I have no idea :) never done much with it. But I'm happy to do some research if that helps.

**Comment by Zaid-Ajaj** [comment]
> In my specific case, the number of files depends on elements from a JSON file. I use the original file for configuration and then generate the output.

I think you might want to use something a lot simpler than Myriad for your use case. I see the benefit of Myriad when your input itself is a F# file with types and code that you want to extend with more functionality on a compile-time bases. However, when your input is a JSON configuration file, then you do something like what I did with [Snowflaqe](https://github.com/Zaid-Ajaj/Snowflaqe): build a dotnet CLI tool that is invoked against the JSON file to generate a full F# project with multiple files and their required dependencies as well as easily consuming nuget packages for your CLI tool. 

The end result is a really nice workflow: whenever you make changes to the JSON config, run the tool again to regenerate the files without having to fight with MSBuild files and tasks.

**Comment by UnoSD** [comment]
@Zaid-Ajaj I'll have a look. But it is too late now, I have put a lot of effort in generating the AST from JSON and it is not worth rebuilding everything from scratch. I did ask around before picking Myriad for F# code generation, but people seemed to only suggest that as an option (and I presumed it was easier to just generate text fs, at the time).

**Comment by Zaid-Ajaj** [comment]
> I have put a lot of effort in generating the AST from JSON and it is not worth rebuilding everything from scratch.

You don't have to rebuild from scratch, you can use the exact same code that you are using now to generate the F# AST and just throw that into the `format` function from Fantomas to get a string of the file contents which you can then reference from a project or create a standalone project with multiple files. 

This is also what Snowflaqe does, it generates F# AST using `FsAst` much like Myriad and then puts the output in a project (project file is also generated by the tool)

**Comment by UnoSD** [comment]
@Zaid-Ajaj I need to give it a try then, thank you for the suggestion.

**Comment by 7sharp9** [comment]
Myriad is also a CLI tool, so it can be used that way too, MSBUILD is optional.

The way I see this working with MSBUILD is something like this:

```xml
    <ItemGroup>
        <Myriad>
            <MyriadFiles>test.json</MyriadFiles>
            <MyriadNameSpace>Test</MyriadNameSpace>
    </Myriad>
    </ItemGroup>
```

I saw having a F# file as input as just one way of doing code generation, one thing that needs fleshing out is the configurations which I feel is more suited to a myriad.toml file rather than complicating MSBUILD with lots of parameters.

**Comment by 7sharp9** [comment]
`<MyriadNameSpace>Test</MyriadNameSpace>` is now depreciated in 0.5.0 by the way.

**Comment by 7sharp9** [comment]
With this you(me) would have to map the matadata in the SomeItem so that it becomes an input parameter into the key value pairs that are given to myriad.  Probably better to just use myriads key value pair config option.

**Comment by 7sharp9** [comment]
```
    Maybe something like this
    <Compile Include=$(MyriadParams)>
      <!-- An example of inline generation, notice no MyriadFile should be specified -->
      <MyriadInlineGeneration>true</MyriadInlineGeneration>
      <MyriadParams>
        <MyriadParam1>1</MyriadParam1>
        <MyriadParam2>2</MyriadParam2>
      </MyriadParams>
    </Compile>
    ```

**Comment by 7sharp9** [comment]
Im not sure if there is still a demand for this issue?

**Comment by UnoSD** [comment]
@7sharp9 I have not touched the project in a while, splitting into multiple files would surely still be beneficial, but I have to be honest and if the feature was added, it's unlikely that I will have time to use it.

Thank you for the help, if that's useful just for myself, I don't mind closing the issue.

**Comment by 7sharp9** [comment]
I don't think this will be easy to add so I'm going to go ahead and close it.
