### ISSUE TITLE
Inaccuracy in README.md

### ISSUE THREAD

**Issue by nbns** [MoiraeSoftware/myriad#73]
Hi. Maybe is there an error in the code?

instead of 
`csharp create (one : Test1) (two : string) (three : float) (four : float32) : Test1 `
should be
`csharp create (one : int) (two : string) (three : float) (four : float32) : Test1`

**Comment by 7sharp9** [comment]
Thanks @nbns I recon I changed it to test recursion or something then it just got committed.   Let me see what its supposed to be.

**Comment by 7sharp9** [comment]
Thanks!
