### ISSUE TITLE
Add myriad.toml to the nuget package so users always get this file, even if empty

### ISSUE THREAD

**Issue by 7sharp9** [MoiraeSoftware/myriad#78]
This must be easy to do?

**Comment by Krzysztof-Cieslak** [comment]
This SO answer has some suggestions: https://stackoverflow.com/questions/10785596/can-nuget-add-a-cs-file-to-the-destination-project

**Comment by Krzysztof-Cieslak** [comment]
However the issue may be that packages in NuGet are done per project, but we'd like to add the `myriad.toml` in solution root (I think?)

**Comment by Krzysztof-Cieslak** [comment]
Maybe instead of doing any magic like that, we could create the file if it doesn't exist as part of the CLI tool?

**Comment by 7sharp9** [comment]
Yeah maybe but touch a blank one if not there.
